name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install and cache dependencies
    - name: Cache boost
      uses: actions/cache@v1.0.3
      id: cache-boost
      with:
        path: ${{ runner.workspace }}/boost
        key: libboost1.65-dev
    - name: Install boost
      env:
        CACHE_HIT: ${{steps.cache-boost.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --force --recursive ~/boost/* /
        else
          sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
          mkdir -p ${{ runner.workspace }}/boost
          for dep in libboost1.65-dev; do
              dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ${{ runner.workspace }}/boost/
          done
        fi
    - uses: ashutoshvarma/action-cmake-build@master
      with:
        source-dir: ${{ runner.workspace }}/shFT
        build-dir: ${{ runner.workspace }}/shFT/build
        run: ls
        cc: gcc
        cxx: g++
        build-type: Debug
        configure-options: -DBOOSTROOT=${{ runner.workspace }}/boost/ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=..
        ctest-options: -VV
        run-test: true
        install-build: true
        parallel: 4
